# Generated by Django 4.0.3 on 2023-07-12 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_restaurant_comment_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='banner',
            new_name='place_pic',
        ),
        migrations.AlterField(
            model_name='kid',
            name='age',
            field=models.DecimalField(decimal_places=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('NEWPLACE', 'newplace'), ('KIDUPDATE', 'menuupdate'), ('FOLLOWED', 'followed'), ('LIKED', 'liked'), ('LIKEDPLACE', 'likedplace'), ('COMMENTED', 'commented')], default='GENERAL', max_length=10),
        ),
    ]
